# Generated by Django 5.1.4 on 2024-12-23 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='other_details',
        ),
        migrations.AddField(
            model_name='product',
            name='other_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_details', to='app.productotherdetails'),
        ),
    ]
