# Generated by Django 5.1.4 on 2024-12-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
