# Generated by Django 5.1.4 on 2024-12-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('image', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('map', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('email', models.JSONField()),
                ('number', models.JSONField()),
            ],
        ),
    ]
