# Generated by Django 5.1.4 on 2024-12-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contact_facebook_contact_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_cost',
            field=models.FloatField(default=70),
        ),
    ]
