# Generated by Django 5.1.4 on 2024-12-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='facebook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='instagram',
            field=models.TextField(blank=True, null=True),
        ),
    ]
