# Generated by Django 5.1.4 on 2024-12-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_visitor_checkout_checkoutitem_checkout_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='products',
        ),
    ]
