# Generated by Django 5.1.4 on 2024-12-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_checkout_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='product',
            field=models.ManyToManyField(related_name='checkouts', to='app.product'),
        ),
    ]
