# Generated by Django 5.1.4 on 2024-12-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_checkout_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='product',
        ),
    ]
