# Generated by Django 5.1.4 on 2024-12-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_checkout_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
