# Generated by Django 5.1.4 on 2024-12-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_checkout_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=10),
        ),
    ]
