# Generated by Django 5.1.4 on 2024-12-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_product_delivery_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_cost',
            field=models.FloatField(default=70),
        ),
    ]
