# Generated by Django 5.1.4 on 2024-12-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_checkoutitem_created_at_checkoutitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutitem',
            name='created_at',
            field=models.DateField(default='2024-12-26'),
        ),
        migrations.AlterField(
            model_name='checkoutitem',
            name='updated_at',
            field=models.DateField(default='2024-12-26'),
        ),
    ]
