# Generated by Django 5.1.4 on 2024-12-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_checkoutitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutitem',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkoutitem',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
