# Generated by Django 5.1.4 on 2024-12-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_checkoutitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='other_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
