# Generated by Django 5.1.4 on 2024-12-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_checkout_other_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_status',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='Cash on Delivery', max_length=20),
        ),
    ]
